// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT3lLm731kYv77wUfclAwkE6vL4gJzyZo',
    appId: '1:310347739256:web:136da01bed092bf8623d8d',
    messagingSenderId: '310347739256',
    projectId: 'eco-grow-e50ea',
    authDomain: 'eco-grow-e50ea.firebaseapp.com',
    storageBucket: 'eco-grow-e50ea.appspot.com',
    measurementId: 'G-FCBDRYE9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDm-Pf9zvwm29WZexIIc6ckOrSmpJhQDg',
    appId: '1:310347739256:android:11931b238bbbf70e623d8d',
    messagingSenderId: '310347739256',
    projectId: 'eco-grow-e50ea',
    storageBucket: 'eco-grow-e50ea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYgIO4tntYP59UYY4K-wpACWV7UzsFX5s',
    appId: '1:310347739256:ios:9125b240a68d4615623d8d',
    messagingSenderId: '310347739256',
    projectId: 'eco-grow-e50ea',
    storageBucket: 'eco-grow-e50ea.appspot.com',
    iosBundleId: 'com.example.ecoGrow',
  );
}
